version: "3.1"
services:
  nginx:
    image: nginx:1.25-alpine3.18 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/auth.conf:/etc/nginx/sites-enabled/auth.conf
      - ./nginx/startpage.conf:/etc/nginx/sites-enabled/startpage.conf
    ports:
      - "8080:80"
    restart: always

  backend:
    image: backend
    build:
      context: ./backend/
      dockerfile: ./Dockerfile

  startpage:
      image: daledavies/jump
      ports:
        - 8123:8080
      volumes:
        - ./startpage/backgrounds:/backgrounds
        - ./startpage/favicon:/favicon
        - ./startpage/search:/search
        - ./startpage/sites:/sites
      environment:
          SITENAME: 'La startpage du test'
          NOINDEX: 'true'
          METRICTEMP: 'true'


